FROM python:3.11.4

LABEL maintainer="Yogamurti Sutanto <yogamurtisutanto@gmail.com>"

# Install Git
RUN apt-get update && apt-get install -y git

# Set the working directory
WORKDIR /telegram-bot

# Clone the Git repository
RUN git clone https://github.com/yogamurti/telegram-shopping-bot.git .

# Install required libraries
RUN pip install -r requirements.txt

ENTRYPOINT ["python"]

CMD ["/telegram-bot/shopping.py"]